/**
 * Test-only helpers: load vendored puzzle/solution fixtures and cross-check the
 * technique solver against the independent oracle solution.
 *
 * Solutions are precomputed and vendored alongside each puzzle file
 * (`<name>.solutions.csv`, line-aligned) — see `tests/fixtures/PROVENANCE.md`.
 * They were generated by a separate backtracking solver and verified unique at
 * generation time, so tests here are fast string comparisons, not re-solves.
 *
 * The core invariant every fixture run asserts is *consistency*: the technique
 * solver may leave a puzzle unsolved (a technique isn't implemented yet), but it
 * must NEVER place a digit that disagrees with the unique solution. A wrong
 * elimination in some future technique surfaces here as a mismatched cell.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parseGrid, serializeGrid } from '../candidates.js';
import { solveAll, type SolveStatus } from '../solver.js';
import type { TechniqueId } from '../step.js';
import type { Grid } from '../grid.js';

const FIXTURE_DIR = join(dirname(fileURLToPath(import.meta.url)), '../../tests/fixtures');

function readLines(file: string): string[] {
  return readFileSync(join(FIXTURE_DIR, file), 'utf8')
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
}

/** Load a fixture CSV as an array of 81-char puzzle strings. */
export function loadPuzzles(file: string): string[] {
  return readLines(file);
}

/**
 * Every puzzle fixture file (the `.csv`s, excluding their `.solutions.csv`
 * companions). Used so the consistency invariant runs over ALL fixtures on each
 * run and automatically covers fixtures added later.
 */
export function listFixtureFiles(): string[] {
  return readdirSync(FIXTURE_DIR)
    .filter((f) => f.endsWith('.csv') && !f.endsWith('.solutions.csv'))
    .sort();
}

export interface PuzzlePair {
  readonly puzzle: string;
  readonly solution: string;
}

/** Load puzzles paired with their vendored oracle solutions. */
export function loadPairs(file: string): PuzzlePair[] {
  const puzzles = readLines(file);
  const solutions = readLines(file.replace('.csv', '.solutions.csv'));
  if (puzzles.length !== solutions.length) {
    throw new Error(
      `Fixture/solution length mismatch in ${file}: ${puzzles.length} vs ${solutions.length}`,
    );
  }
  return puzzles.map((puzzle, i) => ({ puzzle, solution: solutions[i]! }));
}

export interface OracleOutcome {
  readonly puzzle: string;
  readonly status: SolveStatus;
  /** True when the solver fully solved the puzzle to the oracle solution. */
  readonly solved: boolean;
  /** A cell the solver placed that disagrees with the oracle, or null. */
  readonly wrongCell: number | null;
  /** Technique ids the solver applied, in order. */
  readonly techniques: readonly TechniqueId[];
}

/** Run the technique solver on one puzzle and compare with its oracle solution. */
export function checkAgainstOracle(pair: PuzzlePair): OracleOutcome {
  const grid: Grid = parseGrid(pair.puzzle);
  const result = solveAll(grid);

  let wrongCell: number | null = null;
  for (let i = 0; i < 81; i++) {
    const d = grid.placed[i]!;
    if (d !== 0 && String(d) !== pair.solution[i]) {
      wrongCell = i;
      break;
    }
  }

  return {
    puzzle: pair.puzzle,
    status: result.status,
    solved: result.status === 'solved' && serializeGrid(grid) === pair.solution,
    wrongCell,
    techniques: result.steps.map((s) => s.technique),
  };
}

export interface FixtureSummary {
  readonly total: number;
  readonly solved: number;
  readonly wrong: OracleOutcome[];
  readonly outcomes: OracleOutcome[];
}

export function runFixture(file: string): FixtureSummary {
  const outcomes = loadPairs(file).map(checkAgainstOracle);
  return {
    total: outcomes.length,
    solved: outcomes.filter((o) => o.solved).length,
    wrong: outcomes.filter((o) => o.wrongCell !== null),
    outcomes,
  };
}
